program: sweep_train.py
method: bayes
metric:
  name: lars_coco_val_panoptic_with_sem_seg/panoptic_seg/PQ
  goal: maximize

parameters:
  # ──────────────── LR & warm-up ────────────────
  lr:
    distribution: log_uniform_values
    min: 0.00003 # 3e-5
    max: 0.0002 # 2e-4

  warmup_length:
    distribution: uniform
    min: 0.03
    max: 0.10
  warmup_factor:
    values: [0.01, 0.05, 0.1]

  lr_decay_90:
    values: [0.83, 0.87, 0.90]
  lr_decay_95:
    values: [0.90, 0.93, 0.96]

  # ──────────────── Regularisation ──────────────
  weight_decay:
    values: [0.01, 0.03, 0.05, 0.08]
  grad_clip:
    values: [0, 0.01, 0.02]

  # ────────────── Loss balancing ────────────────
  dice_weight:
    values: [3.0, 5.0, 7.0]
  mask_weight:
    values: [4.0, 5.0, 6.0]

  # ─────── Training length ───────
  max_iter:
    values: [4000, 6000, 8000]

early_terminate:
  type: hyperband
  min_iter: 800
  max_iter: 8000
  s: 3